### ISSUE TITLE
showSuccessWithStatus checkmark not showing on iOS 7 first time used

### ISSUE THREAD

**Issue by WouterDS** [TransitApp/SVProgressHUD#198]
Since iOS 7 the checkmark is not visible the first time I use showSuccessWithStatus.
Worked perfectly fine on iOS 5 & 6.

![image](https://f.cloud.github.com/assets/1210628/1171383/d732ddaa-2103-11e3-80ab-0d8b3f81d343.png)

Usage: `[SVProgressHUD showSuccessWithStatus:@"Found location"];`

**Comment by honkmaster** [comment]
Please reopen this issue if it is still active.
