### ISSUE TITLE
overlayView should cover keyboard

### ISSUE THREAD

**Issue by mbigatti** [TransitApp/SVProgressHUD#210]
I noticed that when showing UIAlertViews, Apple overlay view covers also the keyboard. As I have an SVProgressHUD short before an UIAlertView, this inconsistency is noticeable. I think SVProgressHUD overlay also should cover the keyboard.

**Comment by fukemy** [comment]
same problem here, the HUD not overlay https://github.com/nathantannar4/InputBarAccessoryView, im trying to find solution
