### ISSUE TITLE
[iOS7]SVProgressHUD doesn't show in a background block (Potential bug)

### ISSUE THREAD

**Issue by mal3k** [TransitApp/SVProgressHUD#232]
I thought SVProgressHUD would manage that, but it seems not. So I explicitly put the show code into a dispatch block to run it on the main thread:

    [user signUpInBackgroundWithBlock:^(BOOL succeeded, NSError *error) {
        
        [SVProgressHUD dismiss];
        if (!error) {
           
            dispatch_async(dispatch_get_main_queue(), ^{
                [SVProgressHUD showSuccessWithStatus:@"User registered successfully"];

            });
        }else{
            
            dispatch_async(dispatch_get_main_queue(), ^{

                [SVProgressHUD showErrorWithStatus:[error.userInfo valueForKey:@"error"]];
            });
        }
    }];

This still don't work at all, if I replace the SVProgressHUD code with an UIAlertView it will show up. Why it's not working with SVProgressHUD ?

Thanks in advance, and nice library actually :)

**Comment by honkmaster** [comment]
Please reopen this issue if it is still active.

**Comment by xabstan** [comment]
i am resolve a problem:
1. add property 
@property (nonatomic, readonly, getter = isDismissing) BOOL dismissing;
2.add flag
- (void)dismissWithDuration:(NSTimeInterval)duration delay:(NSTimeInterval)delay {
{
     _dismissing = YES;
    // Dismiss if visible (depending on alpha)
    ....
        void (^completionBlock)(void) = ^{
            ....
            _dismissing = NO;
        };
}
3. - (void)showImage:(UIImage*)image status:(NSString*)status duration:(NSTimeInterval)duration rename function with name - (void)showImageSS:(UIImage*)image status:(NSString*)status duration:(NSTimeInterval)duration
4. add delay
- (void)showImage:(UIImage*)image status:(NSString*)status duration:(NSTimeInterval)duration
{
    if(self.isDismissing){
        __weak SVProgressHUD *weakSelf = self;
        dispatch_after(dispatch_time(DISPATCH_TIME_NOW, NSEC_PER_SEC * SVProgressHUDDefaultAnimationDuration),dispatch_get_main_queue(), ^{
            [weakSelf showImageSS:image status:status duration:duration];
        });
    }else{
        [self showImageSS:image status:status duration:duration];
    }
}

- (void)showImageSS:(UIImage*)image status:(NSString*)status duration:(NSTimeInterval)duration
{
       // this is orginal function - (void)showImage:(UIImage*)image status:(NSString*)status duration:(NSTimeInterval)duration code block
}
5. finsh
Thanks Everybody
