### ISSUE TITLE
Not compiling in projects supporting iOS versions prior to iOS7

### ISSUE THREAD

**Issue by luisespinoza** [TransitApp/SVProgressHUD#238]
I'm working with a project that support iOS6 and above.SVProgressHUD is not compiling because, for projects supporting prior versions to iOS 7, the const `SVProgressHUDParallaxDepthPoints` is used but not declared.

The const is declared at line 28, in this code block:

    #if __IPHONE_OS_VERSION_MIN_REQUIRED >= 70000
    static const CGFloat SVProgressHUDRingRadius = 18;
    static const CGFloat SVProgressHUDRingThickness = 4;
    static const CGFloat SVProgressHUDParallaxDepthPoints = 10;
    #else
    static const CGFloat SVProgressHUDRingRadius = 14;
    static const CGFloat SVProgressHUDRingThickness = 6;  
    #endif

Then, is used at lines 749, 750, 753 and 754. Inside the block

    UIInterpolatingMotionEffect *effectX = [[UIInterpolatingMotionEffect alloc] initWithKeyPath: @"center.x" type: UIInterpolatingMotionEffectTypeTiltAlongHorizontalAxis];
    effectX.minimumRelativeValue = @(-SVProgressHUDParallaxDepthPoints);
    effectX.maximumRelativeValue = @(SVProgressHUDParallaxDepthPoints);
        
    UIInterpolatingMotionEffect *effectY = [[UIInterpolatingMotionEffect alloc] initWithKeyPath: @"center.y" type: UIInterpolatingMotionEffectTypeTiltAlongVerticalAxis];
    effectY.minimumRelativeValue = @(-SVProgressHUDParallaxDepthPoints);
    effectY.maximumRelativeValue = @(SVProgressHUDParallaxDepthPoints);

My workaround this has been wrap the second block inside an #if, only for projects supporting above iOS 7.

**Comment by honkmaster** [comment]
Please reopen this issue if it is still active.
