### ISSUE TITLE
show hud problem

### ISSUE THREAD

**Issue by ddrccw** [TransitApp/SVProgressHUD#273]
when presented a view controller which has a player view and orientation setting as below:
```
- (BOOL)shouldAutorotate {
    return YES;
}

- (UIInterfaceOrientation)preferredInterfaceOrientationForPresentation {
    return UIInterfaceOrientationLandscapeRight;
}

- (NSUInteger)supportedInterfaceOrientations {
    return UIInterfaceOrientationMaskLandscapeLeft | UIInterfaceOrientationMaskLandscapeRight | UIInterfaceOrientationMaskPortrait;
}
```
I called the show method, then I found that the hud had a rotation animation in landscape mode.

Finally, in `- (void)showProgress:(float)progress status:(NSString*)string maskType:(SVProgressHUDMaskType)hudMaskType`

I found removing the option `UIViewAnimationOptionBeginFromCurrentState` could fix this problem. Can somebody explain something about it?

**Comment by honkmaster** [comment]
`customizedIndefiniteAnimatedLayer ` does not exist anymore.
