### ISSUE TITLE
Still not working in viewDidLoad?

### ISSUE THREAD

**Issue by allaire** [TransitApp/SVProgressHUD#315]
I had no luck to successfully display SVProgressHUD in `viewDidLoad:`. It only works in `viewDidAppear:`. I saw old issues about this telling us it was fixed, is this still the case or am I doing something wrong?

Thanks

**Comment by mayooresan** [comment]
I tried with 8.3 and same issue occurred. SVProgressHUD not showing up in `ViewDidLoad`. But works just fine if I initiate it in `viewWillLoad`

**Comment by allaire** [comment]
@mayooresan This is working for me now in viewDidLoad with latest swift and latest cocoapods !

**Comment by honkmaster** [comment]
Can this ticket be closed if it is working again?

**Comment by allaire** [comment]
@honkmaster Just investigated this in an Objective-C project I had. This issue depends on the threading timing I think (see Sam's explanation here: https://github.com/TransitApp/SVProgressHUD/issues/60)

From what I see in the code, I don't see any `dispatch_async(dispatch_get_main_queue(), ^{` anymore. I just tried to wrap a method with it:

```objective-c
+ (void)showWithMaskType:(SVProgressHUDMaskType)maskType {
    dispatch_async(dispatch_get_main_queue(), ^{
        [self showProgress:SVProgressHUDUndefinedProgress maskType:maskType];
    });
}
```

and it worked flawlessly in my Obj-c project with multiple UIWindow and UI all in code (showing SVProgressHUD in viewDidLoad). Curiously, I didn't need it in my Swift project with 1 UIWindow and using Storyboard.

Any ideas why the `dispatch_async` is not there anymore?

**Comment by allaire** [comment]
Note that this is currently not working in viewDidLoad only on the root view controller (the one where the app loads). it works correctly in every other viewDidLoad following an action.

**Comment by honkmaster** [comment]
I have no idea why 'dispatch_async' is gone. Here we have to ask @samvermette.

**Comment by hightech** [comment]
Same here. SVProgressHUD in viewDidLoad doesn't work. I tried with iOS 8.4/XCode 6.4 (Swift with header-bridge) and even with the latest SVProgressHUD 1.1.3.

**Comment by allaire** [comment]
@hightech can you confirm it works with my `dispatch_async` code above?

**Comment by hightech** [comment]
@allaire I tried that and it doesn't work. :-(

**Comment by liubomin** [comment]
how to improve My english?

**Comment by sigursalt** [comment]
Using SVProgressHUD 1.1.3
cocoapods-0.37.2
xCode 6.4

Works for me **only if I use GCD**:
        dispatch_async(dispatch_get_main_queue()) {
            SVProgressHUD.show()
        }

When pushing to main thread it works no matter where I put it.

If I don't wrap in the dispatch_async it **only** works in viewDidAppear.

I'm new to iOS development and this is one of my cocoapod trials.  I was sure I was doing everything right and still couldn't get it to paint.  I'm glad I found this conversation.

**Comment by allaire** [comment]
@sigursalt thanks for confirming this on your side!

**Comment by mayooresan** [comment]
To my surprise the one I downloaded a month ago works just fine without `dispatch_asyc` with Swift. I had a hard time with my previous project and it refused to work without `dispatch_async`

**Comment by pablocarreraest** [comment]
@sigursalt thanks for that!
