### ISSUE TITLE
iOS 8: SVProgressHUD Activity indicator is not centered aligned properly in Landscape mode in iOS 8. 

### ISSUE THREAD

**Issue by sumanthness** [TransitApp/SVProgressHUD#333]
Can somebody help me out to fix this issue. I tried by taking the keywindow frame then also the loading Activity Indicator is not centered aligned in Landscape mode in iOS 8 simulators and devices.

**Comment by raul03ma** [comment]
For ios 8.3 it isnt fixed.
![ios simulator screen shot 2 6 2015 13 00 12](https://cloud.githubusercontent.com/assets/4696332/7935250/52eac5c2-0927-11e5-9c4f-fe5c30b29776.png)

**Comment by raul03ma** [comment]
I think I was wrong. It work well on movil phone. The problem was, that it was executed at the simulator. when the activity indicator appears the focus was inside a text field, but the keyboard was hidden, this only can happen at the simulator.
