### ISSUE TITLE
boundingRectWithSize calculate wrong size on ios 7.0.3

### ISSUE THREAD

**Issue by DaidoujiChen** [TransitApp/SVProgressHUD#391]
Hello,

i found a strange crash on stringRect calculate. like image below

![2014-12-28 8 11 20](https://cloud.githubusercontent.com/assets/670441/5563810/1754e296-8ece-11e4-8c54-177f4fdc7583.png)

i will try to find the root cause, thanks.

**Comment by honkmaster** [comment]
Please reopen this issue if it is still active.
