### ISSUE TITLE
IOS 6 -  [SVProgressHUD updatePosition] crash

### ISSUE THREAD

**Issue by aokudan** [TransitApp/SVProgressHUD#392]
This problem has been corrected. We live in serious trouble. Thank you

![screen shot 2014-12-30 at 16 27 31](https://cloud.githubusercontent.com/assets/929594/5579316/3f231350-9041-11e4-9f87-aa62484407c0.png)

**Comment by xiaolanlianhua** [comment]
1000 CoreText 0x309c5d59 TComponentFont::GetRawBoundingBox() const
 CoreText 0x309b8bce TBaseFont::CalculateFontMetrics(bool) const
 CoreText 0x309c5d3e TComponentFont::CalculateFontMetrics(bool) const
 CoreText 0x309b8a14 TBaseFont::InitFontMetrics() const
CoreText 0x309b8850 TBaseFont::GetStrikeMetrics(float, CGAffineTransform const*, bool) const
CoreText 0x309b861e TFont::InitStrikeMetrics() const
CoreText 0x309b85cc CTFontGetAscent + 91
 GraphicsServices 0x34f5b2c4 0x34f5a000 + 4804
 GraphicsServices 0x34f5d3dc GSFontGetLatin1LayoutInfo + 43
UIFoundation 0x37c5849c -[UIFont(UIFont_AttributedStringDrawing) _getLatin1GlyphMapping:andAdvanceMapping:]
UIFoundation 0x37c2ebe6 ___NSStringDrawingEngine
 UIFoundation 0x37c2dcd6 -[NSString(NSExtendedStringDrawing) boundingRectWithSize:options:attributes:context:]
XXXX 0x001f0a4e -[SVProgressHUD updatePosition](SVProgressHUD.m:337)
XXXX 0x001f226a -[SVProgressHUD showProgress:status:maskType:](SVProgressHUD.m:615)
XXXX 0x001efd20 +[SVProgressHUD showProgress:status:maskType:](SVProgressHUD.m:174)
XXXX 0x001efcc4 +[SVProgressHUD showProgress:status:](SVProgressHUD.m:170)

**Comment by pionl** [comment]
Still casuses crash also on IOS7, iOS8 is working well. I've managed to find the way when sometimes it crash. When the viewController is displayed (from modal presentation, I'm also using defines context) and showing the SVProgressHud in viewDidAppear. This crash is occurring only after presenting the modal.

Thank you,

Stack trace:

0
CoreText	
TComponentFont::GetRawBoundingBox() const + 24
1
CoreText	
TBaseFont::CalculateFontMetrics(bool) const + 100
2
CoreText	
TBaseFont::CalculateFontMetrics(bool) const + 100
3
CoreText	
TComponentFont::CalculateFontMetrics(bool) const + 52
4
CoreText	
TBaseFont::InitFontMetrics() const + 64
5
CoreText	
TBaseFont::GetStrikeMetrics(double, CGAffineTransform const*, bool) const + 96
6
CoreText	
TFont::InitStrikeMetrics() const + 64
7
CoreText	
CTFontGetAscent + 120
8
GraphicsServices	
GSFontEnsureExtraData + 256
9
GraphicsServices	
GSFontGetLatin1LayoutInfo + 68
10
UIFoundation	
-[UIFont(UIFont_AttributedStringDrawing) _getLatin1GlyphMapping:andAdvanceMapping:] + 20
11
UIFoundation	
__NSStringDrawingEngine + 3436
12
UIFoundation	
-[NSString(NSExtendedStringDrawing) boundingRectWithSize:options:attributes:context:] + 160
13
Glogster	
SVProgressHUD.m line 345
-[SVProgressHUD updatePosition]
14
Glogster	
SVProgressHUD.m line 722
-[SVProgressHUD showImage:status:duration:maskType:]
15
Glogster	
SVProgressHUD.m line 215
+[SVProgressHUD showImage:status:maskType:]
16
Glogster	
SVProgressHUD.m line 195
+[SVProgressHUD showSuccessWithStatus:maskType:]
17
Glogster	
SVProgressHUD.m line 190
+[SVProgressHUD showSuccessWithStatus:]

**Comment by aokudan** [comment]
Now I IOS 7 devices crashed. 

![screen shot 2015-05-18 at 11 14 47](https://cloud.githubusercontent.com/assets/929594/7676742/29935858-fd4f-11e4-8cc3-47b55a248cac.png)

**Comment by honkmaster** [comment]
The problem with this is: The call is encapsulated and I do not see why it is crashing. Dou you have any kind of more information? I am not able to reproduce.

**Comment by aokudan** [comment]
@honkmaster What kind of information can I give. Because I do not know when the application crash. I can give any specific information you want.

**Comment by hardikdevios** [comment]
@aokudan i was Also having the Same issue
![screen shot 2015-08-02 at 7 14 06 pm](https://cloud.githubusercontent.com/assets/6657591/9026393/3622e664-394b-11e5-9840-695f66c51488.png)

##### So the Problem is Its Setting a ```NaN``` In label frame which display below loading indicator.This is because the Progress number is which i am Getting from API  in totalBytes and expectedBytes is not proper which setting the progress to garbage Number so may be try this case it might get Help to debug the issue  #####

**Comment by pionl** [comment]
Sometimes I get crash when I display the SVProgress HUD (success with message) after the viewController was displayed (with animation, UIModalPresentationCurrentContext).

**Comment by honkmaster** [comment]
Please check @hardikdevios solution.

**Comment by pionl** [comment]
Im sorry, but the @hardikdevios is not usable, the crash occurs also when displaying error or success message (as previous stack trace I've added), the crash is only on iOS7.

**Comment by jds-trisno** [comment]
Excuse me, I also have this crash in my app. 
The user using iOS 7.0.6 and 7.0.4. With iPhone 5, 5s and 5c.
SVProgressHUD version used is 1.1.3

This is part of the crash report :
```
-[SVProgressHUD updatePosition] (SVProgressHUD.m:345) -> (crash here)
-[SVProgressHUD showProgress:status:maskType:] (SVProgressHUD.m:623)
+[SVProgressHUD showProgress:status:maskType:] (SVProgressHUD.m:172)
+[SVProgressHUD showProgress:status:] (SVProgressHUD.m:168)
```
code which calling showProgress :
```
[SVProgressHUD showWithStatus:NSLocalizedString(@"login ...",nil)]; 
```
*Note :(NSLocalizedString part returns proper value)*

I don't understand how to apply @hardikdevios solution on my problem. 

Is there any other workaround or bug fix for this ?

thanks in advance.

**Comment by chaseacton** [comment]
This needs reopened. @hardikdevios's solution doesn't work for everyone. I am simply calling [SVProgressHUD showWithMaskType:SVProgressHUDMaskTypeGradient], not setting progress or anything, and getting this crash occasionally. iOS 9.2, latest SVProgressHUD release. 
![screen shot 2016-01-19 at 4 33 03 pm](https://cloud.githubusercontent.com/assets/3307194/12436487/9dcaab4e-beca-11e5-9971-5880a896a45d.png)

**Comment by honkmaster** [comment]
The problem is your progress might be NaN. This is what makes this crash happen. Please check the input to the method. However, of course I could make asserts into the code ...

**Comment by chaseacton** [comment]
I'm not using [SVProgressHUD showProgress], only [SVProgressHUD showWithMaskType:SVProgressHUDMaskTypeGradient]
