### ISSUE TITLE
Disappear too fast with Chinese status.

### ISSUE THREAD

**Issue by jaybowong** [TransitApp/SVProgressHUD#400]
Really really too fast. Hope there's some methods to customize the time.

**Comment by honkmaster** [comment]
At the moment there is no external method to chnage the duration. However, you can always customize the code on your own. The method you are locking for is `displayDurationForString:`.

**Comment by wangjiebo** [comment]
@honkmaster Thanks. Already did that. 
But I prefer not changing the code to avoid potential problems when SVProgressHUD is updated.
:)

**Comment by honkmaster** [comment]
What are your current settings? Maybe we can change the code in regards to your localization.

**Comment by wangjiebo** [comment]
Apologize first. A HUD with Chinese status disappears just a little bit faster than expected. Not too fast as I said before.
Here's the code our team use for Chinese status.
```
- (NSTimeInterval)displayDurationForString:(NSString *)string {
	// Original
	// return MIN((float)string.length * 0.06 + 0.5, 5.0);

	// Chinese
	return MIN((float)string.length * 0.13 + 0.5, 5.0);
}
```

This duration has not been widely tested by app users. I'll come back to tell how it works.
