### ISSUE TITLE
too flat on white background

### ISSUE THREAD

**Issue by dwery** [TransitApp/SVProgressHUD#402]
what about a border property or a way to make it stand out when the background is white?

**Comment by honkmaster** [comment]
I see this issue too. However, this is exactly how the iOS default components behave...Our goal is to treat the `SVProgressHUD` as a part of iOS. Therefore a border is not intended.

**Comment by dwery** [comment]
it could be made optional. I agree with using the most iOS compliant style, but sometimes a little bit more of flexibility is a plus

**Comment by honkmaster** [comment]
Sure it is. But overall if we start with such small things maintenance gets way more complicated.
