### ISSUE TITLE
Can't show SVProgressHUD in AppDelegate?

### ISSUE THREAD

**Issue by LuaiKalkatawi** [TransitApp/SVProgressHUD#404]
I'm trying to display `SVProgressHUD` in AppDelegate but it seems impossible. This is how I display the Activity Indicator. How I can make it in with `SVProgressHUD` ? Thanks.

    _spinner.center = CGPointMake(190, 380);
    [self.window addSubview:_spinner];
    [self.window bringSubviewToFront:_spinner];

**Comment by yujean** [comment]
In your `AppDelegate`, you establish a `rootViewController`.  In that `rootViewController`, you should only have to simply execute:

`[SVProgressHUD show];`

or

`[SVProgressHUD dismiss];`
