### ISSUE TITLE
Custom progress view

### ISSUE THREAD

**Issue by olejnjak** [TransitApp/SVProgressHUD#405]
Hi,

I think it would be useful to be able to customise the progress animation view as occasionally the default provided view doesn't match the graphics of the app, e.g. the whole app is using standard UIActivityIndicatorView so it would be useful to avoid mixing it with the default animated view of progress HUD.

Thanks

**Comment by honkmaster** [comment]
We intent this component to be like an default iOS one. Therefore we want it to be as simple as possible => no custom progress view.
