### ISSUE TITLE
Incompatible with Google Admob SDK 7.0, SVProgressHUD can not display

### ISSUE THREAD

**Issue by googoodalls** [TransitApp/SVProgressHUD#407]
Hello, Expert, 

I tried the SVProgressHUD, it works fine with Google Admob SDK 6.12.2, but when I upgrad Google Admob SDK 7.0. all the showProgress and [SVProgressHUD showWithMaskType:SVProgressHUDMaskTypeGradient]; are broken.( can not display).

I am pretty much sure that the compatible issue are caused by Google Admob SDK updating . but I think it is a very critical compatible problem, that the UI control owner should be aware of.

I list the reproduce steps here:
1. checkout the google admob sample : https://github.com/googleads/googleads-mobile-ios-examples
2. cd /Users/%YOUR_USER_NAME%/%YOUR_PATH%/googleads-mobile-ios-examples-master/admob/BannerExample
3. open Podfile to add:   pod 'SVProgressHUD', '~> 1.1.2'
3. in the terminal:  pod install  --> to fetch the latest Google Admob SDK 7.0 & SVProgressHUD
4. open "BannerExample.xcworkspace" 
5. in the viewcontroller.m  add the testing code:
[SVProgressHUD showWithMaskType:SVProgressHUDMaskTypeGradient]

6. build & run.

You will find nothing are shown. but if you use xcode "View UI Hierarchy". the view is listed.

I think the reason is the New Google Admob SDK has category the UIWindow to get Data for the user interaction.

I hope the expert here can know this issue . if possible resolve this problem in the official release.

BR

Steven

**Comment by honkmaster** [comment]
Hi, this seems to be a more complex problem. At first, from my opinion it is not ok to write a category that fiddles around with the original functionality. This seems to be the case here with the UIWindow category. However, I am not quite sure how to handle this. At first I would notify Google about this change in their SDK and the negative side effects. In the meantime I will see what I can do. But I can not promise anything, as this is not directly related to this component.

**Comment by googoodalls** [comment]
Hi, honkmaster, 

Understood, I have sent feedback to Google Admob iOS SDK.
and I will update the status when I got the news. 

Have a good day!

BR

Steven

**Comment by RedBrogdon** [comment]
Hey guys, I'm the developer relations engineer that took @googoodalls's question on our forum.  We've added an optimization to our SDK that involves the creating of a new UIWindow, and it looks like it's throwing off the part of SVProgressHUD that looks for the right one onto which to overlay itself. The UIWindow we create is hidden, so it should be easy to filter out of the search.

**Comment by googoodalls** [comment]
Thanks @RedBrogdon ,

I tried to add the condition:  !window.hidden in
 - (void)showProgress:(float)progress status:(NSString*)string maskType: 
it works fine.

@honkmaster ,

I noticed there the code on master branch have including the similar fix already.
Now I am using cocoa-pod. would you mind just update the podspec version 1.1.2 . 
Then I think the issue could be closed. :-)

**Comment by honkmaster** [comment]
Closed with 1.1.3.
