### ISSUE TITLE
Installation via CocoaPods causes image bundle to not be included in target

### ISSUE THREAD

**Issue by andrewjl** [TransitApp/SVProgressHUD#408]
When I install the latest version, I get an error at `NSBundle *imageBundle = [NSBundle bundleWithURL:url];` (line 267) because the `imageBundle` is nil. This looks like it's happening because the image bundle is not included in the target.

**Comment by honkmaster** [comment]
For me, the Bundle is copied and included in the target.

![screen shot 2015-03-15 at 12 03 42](https://cloud.githubusercontent.com/assets/1380397/6655761/608157f0-cb0b-11e4-89cf-20c9a3575ce3.png)

**Comment by honkmaster** [comment]
Any update?

**Comment by andrewjl** [comment]
I tried it in a an example project and was able to reproduce your result. Will have to dig in deeper as to why it wasn't working originally. 

Good chance that it's a misconfiguration on my end so closing this for now.

**Comment by lightice11** [comment]
I'm getting the same error here. If you fixed it @andrewjl help is appreciated :+1:

**Comment by andrewjl** [comment]
Glad to hear you resolved it. 

There's also an issue where the Cocoapods misconfigures the `Pods-TargetName-resources.sh` script when there are multiple targets specified in the podfile. (Such as an app target and a unit test target.) 

Adding the line `install_resource "SVProgressHUD/SVProgressHUD/SVProgressHUD.bundle"` is what fixed it for me.

**Comment by Danyaga** [comment]
Hi guys, i'm actually having this problem. 

I tried to add manually the SVProgressHUD.bundle as hhanesand said but i get the same error.

**Comment by hhanesand** [comment]
What if you try to add the bundle in your main target's copy resources phase? It's definately not the ideal solution, but it might get up and running.

**Comment by Danyaga** [comment]
I did it and it works. THX!

**Comment by honkmaster** [comment]
@andrewjl Is there a solution / idea how I can solve the misconfiguration?

**Comment by honkmaster** [comment]
Hi, we are aware of a problem regarding the Podfile (e.g. #449). It seems that the `SVProgressHUD.bundle` is not copied to the "Copy Bundle Resources" Build Phase. Due to this continuing problem we are searching for someone that could check and help with this problem. We are not using Cocoapods on our own and are happy for pull request.
