### ISSUE TITLE
iOS deployment target for framework

### ISSUE THREAD

**Issue by rock88** [TransitApp/SVProgressHUD#418]
Hello,
I add SVProgressHUD framework to my project and get this warning from Xcode:
`iOS deployment target '8.3' for architecture 'i386' and variant 'normal' is greater than the maximum value '8.2.99' for the Simulator - iOS 8.2 SDK.`
I think need set deployment target to 8.0 or some else...

**Comment by honkmaster** [comment]
If you only add the framework and thus the sources there will be nothing added in regards to your deployment target. This must be done by you. 

However, FYI: The demo project has iOS 6.0 as deployment target.

**Comment by Tboi** [comment]
thanx u so much
