### ISSUE TITLE
Presenting a UIAlertController Alert while using showProgress:status: puts alert behind HUD

### ISSUE THREAD

**Issue by nnhubbard** [TransitApp/SVProgressHUD#419]
I am running a process and using the `showProgress:status:` method to show this processes progress. I also allow tapping of a cancel button to show a `UIAlertController` which can be used to stop the process. However, the alert is shown behind the HUD. This wasn't an issue when simply using the `setStatus` method.

**Comment by honkmaster** [comment]
I will investigate. However, i think this is bad UI (multiple overlays at once, multiple hierachies). From my point of view I would show the Hud with a mask overly and make it tappable. A tap then will cancel the progress.

**Comment by nnhubbard** [comment]
I agree it isn't ideal, but I hadn't thought of a better way. Maybe I should add a second line of text saying "Tap to cancel". Good idea.

**Comment by nnhubbard** [comment]
Is it possible to detect taps on the HUD?

**Comment by honkmaster** [comment]
Just use 'NSNotificationCenter' and listen to 'SVProgressHUDDidReceiveTouchEventNotification'. The tap to cancel string would be one solution I would accept in an app.

**Comment by nnhubbard** [comment]
Can you hide the HUD rather than dismissing it? So that it can be shown with the same progress later?

**Comment by honkmaster** [comment]
I hope this does not sound too harsh: The HUD is a GUI component, GUI is general stupid. GUI should not store any data about progress (this part of the model). The model keeps information about the recent progress and uses this to update the GUI.

**Comment by nnhubbard** [comment]
Yeah, I realize that and I have built it this way.

**Comment by MBhowmick** [comment]
Is there any solution of this problem yet? I am facing the same issue and I need some urgent help.
