### ISSUE TITLE
Swift: HUD only shows up the first time

### ISSUE THREAD

**Issue by arm0nic** [TransitApp/SVProgressHUD#426]
First of all, thank you for the great library! Really useful!

Unfortunately I am kind of stuck implementing SVProgressHUD.
When the app launches, it instantiates a custom location class (NSObject). The user gets notified about wether his location could be found or not. So far everything works like a charm.
And this is my code: 

let rootView = (UIApplication.sharedApplication().delegate as! AppDelegate).window?.rootViewController as! SlideMenuController
...
SVProgressHUD.setBackgroundColor(UIColor.blackColor().colorWithAlphaComponent(0.5))
SVProgressHUD.setForegroundColor(UIColor.whiteColor())
SVProgressHUD.setViewForExtension(rootView.view)
SVProgressHUD.show()
...
SVProgressHUD.showSuccessWithStatus("Location found")

My problem is, I'd like to show notifications in other parts of the app as well, but everytime I implement it somewhere else nothing happens. I tried different views for setViewForExtension but still nothing.

Does someone have a similar problem or a solution for this?

Thanks for helping me :)

**Comment by honkmaster** [comment]
Could you supply a demo program? I do not use Swift at the moment for my projects.

**Comment by mayooresan** [comment]
For me it's not firing at all if we call it in the `ViewDidLoad` function.

**Comment by allaire** [comment]
Working again in 8.3 using Swift!

**Comment by arm0nic** [comment]
I tried different ways but couldn't find a working solution. I ended up using another framework. Still, i'd appreciate if someone could tell me how to fix this.

**Comment by allaire** [comment]
What version of iOS sdk? Using swift with cocoapods use_frameworks! ?

Sent from my iPhone
Envoyé de mon iPhone

**Comment by arm0nic** [comment]
iOS 8.2 (use_frameworks! used). Should I give it another try on iOS 8.3?

**Comment by allaire** [comment]
@arm0nic Your issue might be related to this: https://github.com/TransitApp/SVProgressHUD/pull/303

**Comment by arm0nic** [comment]
Probably, thanks!
