### ISSUE TITLE
Feature Request: Display custom animated views instead of the default ring

### ISSUE THREAD

**Issue by akaralar** [TransitApp/SVProgressHUD#428]
In situations where progress equals `SVProgressHUDUndefinedProgress`, I want to display an animation other than the default ring. Actually I want to replace the default ring in each progress type. Would it be ok to implement this feature? I would be willing to do so if you say it's ok to add this to the project. I would of course be more than willing to discuss the details on how I might move forward with this.

**Comment by mayooresan** [comment]
Yeah ability accept a custom view instead of the default spinner would be an awesome feature.

**Comment by dileepfrog** [comment]
Ditto! Trying to hack the original implementation on a fork now...

**Comment by honkmaster** [comment]
We intent to treat this component like an iOS system one. Therefore we want it to be as simple as possible with almost no customization.
