### ISSUE TITLE
How to use SVProgressHUD in an App Extension?

### ISSUE THREAD

**Issue by MuscleRumble** [TransitApp/SVProgressHUD#432]
I've read the short passage about how to use SVProgressHUD in an App Extension, but I'm still getting errors and I have no idea how to properly use the `SV_APP_EXTENSIONS` macro.

I'm using CocoaPods and I'm not sure where I have to define that macro. Maybe it's easier to just look at this minimal project: https://dl.dropboxusercontent.com/u/11527701/Test.zip

Any idea?

**Comment by MuscleRumble** [comment]
Okay... I've got it... first of all it has to be a preprocessor macro (that one was quite clear). More importantly it doesn't have to be defined in the App Extension target, but in the `Pods-SVProgressHUD` target.

**Comment by rickmak** [comment]
@MuscleRumble But if I manually modify Pods-SVProgressHUD target, it will get erase on next pos install. How you solve this problem.

**Comment by MuscleRumble** [comment]
By using the `post_install` hook of CocoaPods! Just put this in your Podfile:

	post_install do |installer|
		installer.project.targets.each do |target|
			if target.name == "Pods-SVProgressHUD"
				target.build_configurations.each do |config|
					config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)']
					config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'SV_APP_EXTENSIONS'
				end
			end
		end
	end

**Comment by rickmak** [comment]
Thanks, it works.

**Comment by Dids** [comment]
@MuscleRumble Have you managed to get this working using the latest version of Cocoapods?

I'm getting the following when regenerating my workspace:
https://github.com/CocoaPods/CocoaPods/issues/3747

Fixed it by renaming installer.project.targets to installer.pods_project.targets, but even though 'pod update' goes through fine, Xcode is now complaining that extensions can't access sharedApplication, meaning the preprocessor macro didn't register.

**Comment by MuscleRumble** [comment]
I haven't tested the new version of CocoaPods yet, but I was also worried about [Target Deduplication](http://blog.cocoapods.org/CocoaPods-0.38/#target-deduplication). It shouldn't affect App Extensions at all, but I haven't tested it yet.

I'll try the latest version of CocoaPods out on my projects and get back to you.

**Comment by Dids** [comment]
I actually might've solved it. I was using Pods-MyExtension-SVProgressHUD before as the target name, but I switched back to just using "SVProgressHUD" as the name, which seems to work with the latest Cocoapods.

**Comment by MuscleRumble** [comment]
Alright, nice! :D Out of curiosity, do you have two Pod targets for SVProgressHUD or only one now? The thing is: I would like to have two targets, one for the main project, one for the extension. Because I wouldn't want to set `SV_APP_EXTENSIONS` on the main project. That's why I hope that target deduplication doesn't affect app extensions.

**Comment by Dids** [comment]
I've defined a "shared" list of pods that includes SVProgressHUD, which I then include in both the main app target and the extension target (in the Podfile), like so:

```objc
def shared
pod 'SVProgressHUD'
end

target 'MyApp' do
pod 'SomePod'
shared
end

target 'MyAppExtension' do
pod 'SomeOtherPod'
shared
end
```

Previously in the post_install, I was looking for the SVProgressHUD pod that was exclusively built for my extension, then (and only then) setting the preprocessor macro. Now, with the changes to Cocoapods, it doesn't list target-specific pods anymore (no idea why), so I had to "globally" set SV_APP_EXTENSIONS in post_install.

**Comment by Dids** [comment]
For some strange reason, I'm now getting duplicate symbols for each pod though, right after updating Cocoapods.

**Comment by Dids** [comment]
Okay, so it turns out I just had to remove derived data, and remove any MyApp-PodName includes from Build Settings. Seems to compile now with the latest Cocoapods.
I also moved the post install script inside the extension's target definition, so who knows, maybe that will only set the flag when the extension is compiled.

**Comment by MuscleRumble** [comment]
Posted an issue on CocoaPods: https://github.com/CocoaPods/CocoaPods/issues/3951

In short: I don't know how to set the preprocessor macro `SV_APP_EXTENSIONS` so that it only affects the app extension. Have you figured something out @Dids?

**Comment by MuscleRumble** [comment]
Just to keep everybody in the loop who's interested. I'm using now this `pre_install` hook to enforce duplication on `SVProgressHUD` from https://github.com/CocoaPods/CocoaPods/issues/3794#issuecomment-129791907.

```ruby
pre_install do |installer|
    pod_targets = installer.pod_targets.flat_map do |pod_target|
        pod_target.name == "SVProgressHUD" ? pod_target.scoped : pod_target
    end
    installer.aggregate_targets.each do |aggregate_target|
        aggregate_target.pod_targets = pod_targets.select do |pod_target|
            pod_target.target_definitions.include?(aggregate_target.target_definition)
        end
    end
end
```

After that you can use the `post_install` hook, which has been discussed in the beginning, to add the preprocessor macro `SV_APP_EXTENSIONS`.

I think this is the best solution for now. It would be great if that "duplication enforcement" would be part of the Podfile DSL in future.

**Comment by honkmaster** [comment]
Hi, we are aware of a problem regarding the Podfile (e.g. #449). It seems that the `SVProgressHUD.bundle` is not copied to the "Copy Bundle Resources" Build Phase. Due to this continuing problem we are searching for someone that could check and help with this problem. We are not using Cocoapods on our own and are happy for pull request.

**Comment by NSFish** [comment]
In case anyone come across this issue, now you can simply do
```ruby
post_install do |installer|
    installer.project.targets.each do |target|
        if target.name == "SVProgressHUD-MyExtensionTargetName-Pods"
            target.build_configurations.each do |config|
                config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)']
                config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'SV_APP_EXTENSIONS'
            end
        end
    end
end
```

Cocoapods will generate 2 seperated targets in Pods project, one with "SV_APP_EXTENSIONS" setup and one without it.

**Comment by suhaa18** [comment]
Hello everybody!

First thank you for tobihagemann help! 

By the way, if I use above configuration, spinner is running in app side, but not running in share extension side. Of course, in share extension side, any issue not happened, but spinner not running even though I configured additionally call setViewForExtension: from share extensions view controller with self.view.

If I use only post_instll,  spinner is only running in extension side, not running in app side.

Below is my podfile:

```
pre_install do |installer|
    pod_targets = installer.pod_targets.flat_map do |pod_target|
        pod_target.name == "SVProgressHUD" ? pod_target.scoped : pod_target
    end
    installer.aggregate_targets.each do |aggregate_target|
        aggregate_target.pod_targets = pod_targets.select do |pod_target|
            pod_target.target_definitions.include?(aggregate_target.target_definition)
        end
    end
end

target 'myTest' do
      pod 'SVProgressHUD', '2.1.2'
end

target 'share' do
     pod 'SVProgressHUD', '2.1.2'
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        puts target.name
        if target.name == "SVProgressHUD-Pods-share"    
            target.build_configurations.each do |config|
                config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)']
                config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'SV_APP_EXTENSIONS'
            end
        end
    end    
end
```

I want to know how to showing spinner both of app and share extension side.
Thank you.

**Comment by pablogeek** [comment]
Hello guys, since XCode 10, I'm getting duplicated issue in this solution. Do we have another solution for this?

**Comment by himanshujamnaniopenxcell** [comment]
> post_install do |installer|
>     installer.pods_project.targets.each do |target|
>         puts target.name
>         if target.name == "SVProgressHUD-Pods-share"    
>             target.build_configurations.each do |config|
>                 config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)']
>                 config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'SV_APP_EXTENSIONS'
>             end
>         end
>     end    
> end

Not working for me guys?

**Comment by fukemy** [comment]
any new solution here?
