### ISSUE TITLE
How to animate HUD with custom image?

### ISSUE THREAD

**Issue by LeeKyungMoon** [TransitApp/SVProgressHUD#434]
I use [SVProgressHUD showImage:[UIImage]  status:[NSString]] and i ran it. There are two problems, first, I want to shake my HUD and I want to enlarge my image, Is it possible ?

**Comment by honkmaster** [comment]
This is not possible at the moment.

**Comment by zeeshanhaider-devbatch** [comment]
I have added support for showing GIF image in the SVProgressHUD with a public method.

I used SDWebImage method to show GIF in UIImageVIew

- (void)showGIFImage:(NSString *)imageName status:(NSString*)string duration:(NSTimeInterval)duration{
    self.progress = SVProgressHUDUndefinedProgress;
    [self cancelRingLayerAnimation];
    
    if(![self.class isVisible]){
        [self.class show];
    }
self.imageView.image = [UIImage sd_animatedGIFNamed:imageName];
    self.imageView.hidden = NO;
    
    self.stringLabel.text = string;
    [self updateHUDFrame];
    [self.indefiniteAnimatedView removeFromSuperview];
    if([self.indefiniteAnimatedView respondsToSelector:@selector(stopAnimating)]) {
        [(id)self.indefiniteAnimatedView stopAnimating];
    }
    
    if(self.defaultMaskType != SVProgressHUDMaskTypeNone){
        self.overlayView.userInteractionEnabled = YES;
        self.accessibilityLabel = string;
        self.isAccessibilityElement = YES;
    } else{
        self.overlayView.userInteractionEnabled = NO;
        self.hudView.accessibilityLabel = string;
        self.hudView.isAccessibilityElement = YES;
    }
    
    UIAccessibilityPostNotification(UIAccessibilityScreenChangedNotification, nil);
    UIAccessibilityPostNotification(UIAccessibilityAnnouncementNotification, string);
    
    //self.fadeOutTimer = [NSTimer timerWithTimeInterval:duration target:self selector:@selector(dismiss) userInfo:nil repeats:NO];
    //[[NSRunLoop mainRunLoop] addTimer:self.fadeOutTimer forMode:NSRunLoopCommonModes];
}

**Comment by honkmaster** [comment]
Good idea. However, we will not support this as `SVProgressHUD` should remain independent from other libraries like `SDWebImage`.

**Comment by zeeshanhaider-devbatch** [comment]
Ok leave the SDWebImage gif method, We can include our own method to load gif into UIImageView.
Replace : self.imageView.image = [UIImage sd_animatedGIFNamed:imageName]; with the method from the attached category.

[Archive.zip](https://github.com/SVProgressHUD/SVProgressHUD/files/124492/Archive.zip)

**Comment by ramakrishna013** [comment]
@honkmaster Is it possible to use the `animationImages` in the SVprogressHUD  `void)showImage:(UIImage*)image status:(NSString*)status duration:(NSTimeInterval)duration`  method??
