### ISSUE TITLE
Why iOS 6.1 target, not 6.0?

### ISSUE THREAD

**Issue by ealeksandrov** [TransitApp/SVProgressHUD#436]
In podspec: `s.platform = :ios, '6.1'`. Gives me warning for deployment target 6.0. Why iOS 6.1 was chosen?
From [API diffs](https://developer.apple.com/library/ios/releasenotes/General/iOS61APIDiffs/) I can't see anything interesting.

**Comment by honkmaster** [comment]
Can you provide a working PR?

**Comment by ealeksandrov** [comment]
I would be happy to provide one, but I don't know why iOS 6.1 was chosen initially.
Trace leads to this commit: 04221588c10a4d6ca77624162aed8bb01d69e46c

**Comment by honkmaster** [comment]
I also do not have any idea, even if it was my commit ;) ...
