### ISSUE TITLE
Support iPad multitasking in iOS 9

### ISSUE THREAD

**Issue by phix23** [TransitApp/SVProgressHUD#440]
SVProgressHUD uses `UIScreen.mainScreen.bounds` in some places to layout views on the screen. It should use `[UIApplication sharedApplication].keyWindow.bounds` instead so that the HUD always displays in the center of the application frame, not the center of the screen. This is particularly important to adapt for iPad multitasking in iOS 9.

**Comment by honkmaster** [comment]
Could you please provide a pull request, very good and valid idea.

**Comment by phix23** [comment]
Note that UIAlertView has the same problem and is deprecated in iOS 9. The alert can be shown offscreen when the app runs in split-screen. UIAlertController doesn't have this problem. Maybe SVProgressHUD should be a presentation UIViewController too. Then it could react to trait collection changes appropriately.

**Comment by emirandm** [comment]
Hello, Did the pull request was created? I came across the same issue plus one more. I replace it with (and the other places)

CGRect frame = [[UIApplication sharedApplication] keyWindow].bounds;
        frame = frame.size.width==0?[[UIScreen mainScreen] bounds] : frame;
        sharedView = [[self alloc] initWithFrame:frame];

Sometimes if the keyWindow is not in screen yet or is in process of being show, keywindow will return a frame with 0 width and height so it is good idea to check it.

**Comment by honkmaster** [comment]
The PR was created and merged.
