### ISSUE TITLE
Progress HUD Position Is Not Centered When Keyboard Is Shown

### ISSUE THREAD

**Issue by Jayvd** [TransitApp/SVProgressHUD#443]
Hi, Is there a way to force the HUD position to stay where it is??

I am using this HUD on the Login Page, once user press enter. The HUD appears, and the keyboard dismiss. 

The HUD appears to be in the higher position and it goes down to the center as the keyboard is dismissing.  

Is there any way I could disable this behaviour? 

Thanks

**Comment by honkmaster** [comment]
Not via API. However you could fiddle around with 'visibleKeyboardHeight' in 'SVProgressHud.m'.
