### ISSUE TITLE
HUD is not visible on iOS9

### ISSUE THREAD

**Issue by stasix** [TransitApp/SVProgressHUD#446]
compiling using XCode 7 beta2. iOS9 beta 2.

**Comment by honkmaster** [comment]
I am currently updating my own apps to iOS 9, some of the include this HUD. On all of them the HUD appeared correct (simulator and 6+). Do you have some more hints?

**Comment by stasix** [comment]
Sorry, it was a different issue where I had another window, and HUD was not appearing on the top most window.
