### ISSUE TITLE
SVProgressHUD caused video playing dark

### ISSUE THREAD

**Issue by dengzhp** [TransitApp/SVProgressHUD#451]
I have an app playing video in full screen, I call  [SVProgressHUD show];  when  loading video. 

But it caused the player viiew hidden, only sound.  Without ``[SVProgressHUD show]`` is ok.

    - (void)moviePlayBackDidChange:(NSNotification *)aNotification {
    
        MPMovieLoadState loadState = moviePlayer.loadState;
    
        BOOL isMoviePlayable = (loadState == (MPMovieLoadStatePlaythroughOK|MPMovieLoadStatePlayable));
        if (isMoviePlayable) {
            [SVProgressHUD dismiss];
        }
    
        if ((loadState == MPMovieLoadStateUnknown || loadState == MPMovieLoadStateStalled) &&
            (moviePlayer.playbackState == MPMoviePlaybackStatePlaying)) {
    
            //this line caused problem.
            [SVProgressHUD show];  
       } 
     }

**Comment by honkmaster** [comment]
Could you provide a small sample project?

**Comment by dengzhp** [comment]
@honkmaster I found it need some condition to reproduce it, the video stream has to be on local server, I make a demo project  https://github.com/dengzhp/test-hud , thank you
