### ISSUE TITLE
can you help me ？

### ISSUE THREAD

**Issue by xhp281** [TransitApp/SVProgressHUD#455]
Hello I now want to achieve a result, how to adjust the display position has been centered, not change because of the keyboard? Thank you very much

**Comment by honkmaster** [comment]
I do not really understand your problem.

**Comment by xhp281** [comment]
我想要让这个显示框一直居中，在键盘退下的时候不跟着键盘移动，这个是要修改frame么？

**Comment by honkmaster** [comment]
I also don't understand chinese.

**Comment by liubomin** [comment]
不用

**Comment by xuyunan** [comment]
He means can hud view always in center of the screen? even keyboard is displaying. : ]

**Comment by honkmaster** [comment]
Ok, now i understand. This is related to #443. At the moment there is no way to achieve this behavious without fiddling witht the code base. One approach would be to change 'visibleKeyboardHeight' in 'SVProgressHud.m'.

**Comment by xhp281** [comment]
I know, I just saw。I blocked a notice also achieved， thank you 。^_^

**Comment by liubomin** [comment]
你是怎样提高英文的啊！感觉好牛的！










在 2015-07-17 20:07:37，"酸菜鱼茅_" <notifications@github.com> 写道：


I know, I just saw。I blocked a notice also achieved， thank you 。^_^
