### ISSUE TITLE
setBackgroundColor , setForegroundColor removed

### ISSUE THREAD

**Issue by zeeshankhan** [TransitApp/SVProgressHUD#465]
Previously, there was a `setBackgroundColor:` and ` setForegroundColor` methods and this was removed. Our app uses this method and we preferred setting a custom color.

Was there a technical limitation or something else that caused this method to be removed? If not, is it possible to deprecate the method if that's no longer the preferred way?

Thanks for this amazing library. Several of my apps depend on it.

**Comment by honkmaster** [comment]
Within the scope of #384 We decided to simplify 'SVProgressHUD'. From the feedback we got, many people always use the default configuration with no custom colours. Therefore, I decided to make a "clean" cut and not deprecate the methods. Explanation of this is, that at the moment I am the only maintainer and want to keep the cognitive load as small as possible. Please see the current commits as a kind of 'SVProgressHUD' 2.0.

A quick fix four your problem might be to change 'foregroundColorForStyle:' and 'backgroundColorForStyle:' in 'SVProgressHUD.m'.

**Comment by taviscaron** [comment]
Styling support doesn't have to replace `setBackgroundColor:` and `setForegroundColor:`. It can override these settings and vice versa. I used the library with configured 50% alpha of the bg. Now I can't do this w/o any special deals. MaskTypeBlack does almost the same but user interactions is not allowed. It's very important for a library to be configurable as wide as it possible.

Btw, not sure, that `UIAlertController` is a good example. It's on how to say.. another styling level. It has system style and coloring. But the SVProgressHUD is closer to your app and your app's design.

Thanks.

**Comment by honkmaster** [comment]
You are rigth somehow, however we want to see 'SVProgressHUD' like if it was an iOS-System-Component. However, feel free to submit a PR (by keeping it as simple as possible).

**Comment by GabrielCartier** [comment]
I disagree with the comparaison to UIAlertView but reading the PR, I got the reasons why it cannot be changed. I didn't really look at the code thoroughly, but having some customization would be nice.

On another note, I think you guys should follow stricter versionning as the jump from 1.1.2 to 1.1.3 deletes a lot of method and could make the pod unusable. Since it is suggested to use the head, it might cause some problems. Just a suggestion.

**Comment by GabrielCartier** [comment]
Sorry, my bad, 1.1.3 is still compatible. I'm guessing it will be for a 2.0 which makes sense. My fault as I was using the head.

**Comment by honkmaster** [comment]
First: 1.1.3 is still compatible, As mentioned a few hours ago the current changes are targeting 2.0. We do not suggest to use the head, we just mention that if you want to use the latest features use ':head'. And I stand by the words written: I am very careful what I push to the master. The current changes are used in two of my apps since Q1, 2015 and are very stable. 

Second: I understand all of your concerns and will rethink the simplification. Give me a few hours please.

**Comment by GabrielCartier** [comment]
Yea, I stand corrected for the versioning, my bad :)

As for the changes, is there a discussion somewhere people can participate in for this?

**Comment by honkmaster** [comment]
What about right here?

**Comment by GabrielCartier** [comment]
I'll check a bit more your PR and will think about it too.

**Comment by adrum** [comment]
How about implementing UIAppearance for these properties? Seems like a very 'iOS-System-Component' thing to do.

http://petersteinberger.com/blog/2013/uiappearance-for-custom-views/

**Comment by honkmaster** [comment]
Cool idea. However, I am thinking about an approach where we might add a "third" 'enum' in 'SVProgressHUDStyle' like 'SVProgressHUDStyleCustom'. If this enum is set we could use the 'backgroundColor' and 'foregroundColor'. 

The UIAppearance is very fancy. If we want to use this approach, we should apply it to every UI-property like 'ringThickness', 'font', 'cornerRadius' etc.

**Comment by adrum** [comment]
I added the rest of the UIAppearance properties to pull request #469, including corner radius. I also added the SVProgressHUDCustom to the style enum. I think that approach works well.

**Comment by honkmaster** [comment]
I wanted to merge this feature, however as I was doing so, I recognised that `UI_APPEARANCE_SELECTOR` is not available in iOS6, which is still supported by this component.

**Comment by adrum** [comment]
iOS 6 has support for UIAppearance. I pulled in the latest changes into my PR, added animation type as a UIAppearance property, and enabled UIAppearance for iOS 6.
