### ISSUE TITLE
"_OBJC_CLASS_$_SVRadialGradientLayer" not found for architecture x86_64

### ISSUE THREAD

**Issue by rduboiscortex** [TransitApp/SVProgressHUD#467]
I keep getting this issue since the new update this morning. I thought that adding QuartzCore.framework to our project would fix the issue but unfortunately it doesn't. 

Here is the error log :

Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_SVRadialGradientLayer", referenced from:
      objc-class-ref in SVProgressHUD-C90AE29E963210B5.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by honkmaster** [comment]
Are you using cocoapods?

**Comment by iNiKe** [comment]
I'm in such trouble.
I've cleaned my project and build folder, still no success.
iOS 9.0, Xcode 7.0 (7A220).
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_SVRadialGradientLayer", referenced from:
      objc-class-ref in SVProgressHUD.o
ld: symbol(s) not found for architecture x86_64

Investigating...

**Comment by iNiKe** [comment]
Now i've fixed it, and here is my solution.
I was using old SVProgressHUD version, added directly to my project source tree without any Pods.
I've updated only SVProgressHUD folder on disk with latest one.
Files in project source tree were: SVProgressHUD.* and SVIndefiniteAnimatedView.*

So the solution - is to re-add SVProgressHUD folder in source tree or just add missing files from new source (SVRadialGradientLayer.*).
Thats it! =)

PS: Still don't like to use Cocoapods...

**Comment by mikenew12** [comment]
Just had the same issue and the same resolution. This issue can probably be closed since it's really not the fault of SVProgressHUD.

And +1 for not using Cocoapods.

**Comment by honkmaster** [comment]
Hi, we are aware of a problem regarding the Podfile (e.g. #449). It seems that the `SVProgressHUD.bundle` is not copied to the "Copy Bundle Resources" Build Phase. Due to this continuing problem we are searching for someone that could check and help with this problem. We are not using Cocoapods on our own and are happy for pull request.

**Comment by takamisaki** [comment]
I also meet this issue, and solved it, like this:
I am using the most update version and today is 25,Jan, 2017
Solution:
1. Delete all SVProgressHUD files in your project, but you can leave your code.
2. Drag new SVProgressHUD folder into your xcode project, SELECT "**Copy if needed**" AND "**Create Group**", DO NOT check the "**Create Group Reference**"
3. Add related bundle and framework as offical usage said
4. Done 💯
