### ISSUE TITLE
iOS9 new feature splitview : SVProgressHUD not showing correclty

### ISSUE THREAD

**Issue by ayla08** [TransitApp/SVProgressHUD#470]
Hi everyone,
I'm working on implementing splitview (new feature for ipad on ios 9) on my application. 
When i'm on half screen or 1/3, It does not show correctly.
I think, it is because it's not based on application frame..
![simulator screen shot 27 aout 2015 11 00 52](https://cloud.githubusercontent.com/assets/2813105/9516768/3bda4dae-4cab-11e5-858f-8ad54c7a89dd.png)

Does someone have a quick fix?

Thank you

**Comment by honkmaster** [comment]
Are you using cocoapods?

**Comment by ayla08** [comment]
Yes I'm using cocoaPods, and the library version is : 1.1.3

**Comment by honkmaster** [comment]
There is already a fix on the `:head`. I will submit this as 2.0 soon to cocoapods.

**Comment by ayla08** [comment]
Thank you for your answer, do you know on which date it will be available on Cocoapods? 
Thank you again

**Comment by honkmaster** [comment]
I think sunday evening, monday morning next week.

**Comment by honkmaster** [comment]
Just a quick update, the new cocoapods version will come soon, I want to merge #469 before release, because this is a very important feature.

**Comment by ayla08** [comment]
Can you tell me when please? Because I really need to finish this app version on this week, I tried with "head" the problem seems fixed but there was other problems.. thank you very much.

**Comment by honkmaster** [comment]
2.0-beta is on cocoapods finally.

**Comment by honkmaster** [comment]
Hi, we are aware of a problem regarding the Podfile (e.g. #449). It seems that the `SVProgressHUD.bundle` is not copied to the "Copy Bundle Resources" Build Phase. Due to this continuing problem we are searching for someone that could check and help with this problem. We are not using Cocoapods on our own and are happy for pull request.
