### ISSUE TITLE
Resize custom SVProgressHUD

### ISSUE THREAD

**Issue by NBibikov** [TransitApp/SVProgressHUD#473]
Hi! Thanks for great tool!
Can i change size of custom SVProgressHUD view with indicator? I want make it smaller

**Comment by honkmaster** [comment]
Hi Nick,

do you want to change the overall size of the HUD, or do you want to change the size of the spinner / the imeages?

BR 

Tobi

**Comment by NBibikov** [comment]
I want change the overall size of the HUD

**Comment by honkmaster** [comment]
In `updateHUDFrame:` are two constants `hudWidth` and `hudHeight` (in the first two lines). You could try to change these and see if this is sufficient for you. If more people request this feature, we could discuss about bringing this to the official source.

**Comment by NBibikov** [comment]
Thanks for quick reply! Yes, this is will be great have opportunity change it with official API

**Comment by duyklinsi** [comment]
Hi honkmaster!

I want to change the size of the spinner. Where can I edit it?

**Comment by honkmaster** [comment]
Use `setRingRadius:`.

**Comment by tariqul000** [comment]
Hi honkmaster!
setRingRadius may be not working for me .
I use this  
SVProgressHUD.setRingRadius(CGFloat(10.0))

**Comment by baiyidjp** [comment]
> In `updateHUDFrame:` are two constants `hudWidth` and `hudHeight` (in the first two lines). You could try to change these and see if this is sufficient for you. If more people request this feature, we could discuss about bringing this to the official source.

Can I change this width without modifying the source code?
