### ISSUE TITLE
Create setter for time per character

### ISSUE THREAD

**Issue by henriqueiv** [TransitApp/SVProgressHUD#474]
Now we have 0.06 fixed as time constant for each character. It would be nice if we could change that. I'm developing a project for people with difficulty to read, so the time as is calculated today may be not enough for the user to read.

I already changed for fit my use but I think that this would be interesting to implement here.

**Comment by honkmaster** [comment]
What about a delegate method, which will be called for each string that should be displayed?

**Comment by henriqueiv** [comment]
It would work. And if it is not implemented could use the default calculation to keep the current behavior.

**Comment by henriqueiv** [comment]
Something like this for example...
```
- (NSTimeInterval)displayDurationForString:(NSString*)string{
   return delegate ? self.delegate.displayDurationForString(string) : MIN((float)string.length*0.06 + 0.5, 5.0);
}
```

**Comment by honkmaster** [comment]
I did a rethink. Delegate does not really work here, this is because the hud has no real delegate, because it is shown by many view controllers. What about a subclass for you?

**Comment by henriqueiv** [comment]
Yeah, you're right, but you mean create a subclass for my case only or create it an make a pr?

**Comment by honkmaster** [comment]
I would prefer we move `displayDurationForString` to the public scope and then you could create a ObjectiveC `category`.

**Comment by henriqueiv** [comment]
That's what I though initially, besides, I saw this pr (https://github.com/TransitApp/SVProgressHUD/pull/151) but I don't know if you're gonna merge it to master or do something else.
