### ISSUE TITLE
Not custom color and custom background after update

### ISSUE THREAD

**Issue by antons81** [TransitApp/SVProgressHUD#475]
Hi,

I have updated your framework via cocapods and all my custom colors and backgrounds gone away

SVProgressHUD.setDefaultMaskType(.Clear)
        SVProgressHUD.setBackgroundColor(UIColor.clearColor())
        SVProgressHUD.setRingThickness(3)
        SVProgressHUD.setAnimationCurve(UIViewAnimationCurve.Linear)
        SVProgressHUD.setForegroundColor(UIColor(red:0.92, green:0.53, blue:0.14, alpha:1))
        SVProgressHUD.show()

This is my code that didn't changed, please check this issue

**Comment by honkmaster** [comment]
Sorry for the issue. You have to add `setDefaultStyle()` with `SVProgressHUDStyleCustom`.

**Comment by antons81** [comment]
Thanks it's working now, but background square is still present behind spinner

**Comment by honkmaster** [comment]
Could you provide a screenshot? It is working for me. 
![ios simulator screen shot 02 sep 2015 21 02 53](https://cloud.githubusercontent.com/assets/1380397/9641258/1ebef3d6-51b6-11e5-96a9-fcbbe116e46a.png)

**Comment by antons81** [comment]
![img_4134](https://cloud.githubusercontent.com/assets/4199536/9642621/e0cb5a5a-51c5-11e5-87ca-ae6da4be5b92.PNG)

I set clear color on spinners backgroud. Before I haven't seen this square on clear color.

**Comment by honkmaster** [comment]
Ok, I think I now understand what you mean. So you only want the spinner and nothing else?

**Comment by antons81** [comment]
Yep, like it was before :)

**Comment by honkmaster** [comment]
Ok. The square is from the now "live blurring" mask. I have to remove / hide this mask when the background is transparent. I had not thought about this (i have to be honest) quite uncommon use case of a clear bg. Will fix soon, sorry.

**Comment by antons81** [comment]
No prb, thank you. please update me, when I should update cocoapods repository. But without square background it seems more elegant, isn't it? It was before until last update.

**Comment by antons81** [comment]
If you don't want to remove it from origin. Tell me where I could change it for my self.

**Comment by honkmaster** [comment]
The component was never intended to use without the "square", see this gif: ![SVProgressHUD](http://f.cl.ly/items/2G1F1Z0M0k0h2U3V1p39/SVProgressHUD.gif)

However you are right, this is a bug: Clear is clear and thus there should be no square.

**Comment by ramakrishna013** [comment]
Hi, I added an image to the SVProgressHud By using this method: [self showImage:image status:nil];
Originally my image is in green color. After adding my image color is showing like the gray color. Why?How can i get it original color?

**Comment by Bharath-MallowTech** [comment]
Hi, Is this issue issue fixed ? Can we show only the spinner and nothing else with the current updated library ?

I have used the following steps and I got only empty screen with blur background.
[SVProgressHUD setDefaultMaskType:SVProgressHUDMaskTypeCustom];
[SVProgressHUD setBackgroundColor:[UIColor clearColor]];

Can you please guide me how to achieve this behaviour ?

**Comment by Bharath-MallowTech** [comment]
Hi, Is this issue issue fixed ? Can we show only the spinner and nothing else with the current updated library ?

I have used the following steps and I got only empty screen with blur background.
[SVProgressHUD setDefaultMaskType:SVProgressHUDMaskTypeCustom];
[SVProgressHUD setBackgroundColor:[UIColor clearColor]];

Can you please guide me how to achieve this behaviour ?

**Comment by ramakrishna013** [comment]
@Bharath-MallowTech To change the background color of the SVProgressHUD you can use the below lines of code. By using that code i've showing a white background for SVProgressHUD.

               `SVProgressHUD.setDefaultMaskType(.custom)
                SVProgressHUD.setBackgroundColor(UIColor.white)
                SVProgressHUD.setBackgroundLayerColor(UIColor.white)`

**Comment by Bharath-MallowTech** [comment]
@ramakrishna013 : Thank you it worked when I tried your code on actual project where I have installed the library using pod & applied the properties in swift, actually I tried above code in Objective C in Demo before it didn't work there.
I don't know wether there is any issue with the Demo app. Thanks for your help 👍

**Comment by tanalavijay** [comment]
I want that Spinner on the UIView Which i designed

**Comment by honkmaster** [comment]
@tanalavijay Your english is not very clear. I do not understand your issue.

**Comment by YogendraPatel** [comment]
@honkmaster how to change only ring color, i want backround "live blurring" as it is.
