### ISSUE TITLE
Cannot customize SVProgressHUD globally in AppDelegate.

### ISSUE THREAD

**Issue by kunass2** [TransitApp/SVProgressHUD#477]
I installed `SVProgressHUD` by cocoas and then in AppDelegate I added:

`SVProgressHUD.setBackgroundColor(UIColor.redColor())`

but it doesn't have influence on what is going on in the app. I use it in following way:

`SVProgressHUD.show()`

and result is:

![simulator screen shot 05 sep 2015 08 10 23](https://cloud.githubusercontent.com/assets/9480650/9698008/af10c270-53a5-11e5-8783-f26af8d8ff8b.png)

**Comment by honkmaster** [comment]
It is working for me in the demo project (see screenshot). 

<img width="1174" alt="screen shot 2015-09-05 at 21 01 15" src="https://cloud.githubusercontent.com/assets/1380397/9700796/6184e376-5411-11e5-9b94-4b634c03c66d.png">

**Comment by kunass2** [comment]
I installed this via cocoapods from HEAD branch. And then attach needed files within bridging header. Did you do the same?

**Comment by kunass2** [comment]
I forgot about set default style, but there is no such method in my version. Is it ok?

**Comment by honkmaster** [comment]
I used head but no Swift. The style method should be in head, maybe there is a problem with the bridging header?

**Comment by kunass2** [comment]
It is ok now. I changed my previous answer. Thanks.
