### ISSUE TITLE
Bad_Access

### ISSUE THREAD

**Issue by ghost** [TransitApp/SVProgressHUD#478]
When internet is not reachable or could not connect to server or request timed out , this kind of situation arises at that time svprogress hud shows bad_access error some time in hud view or some times in string label in svprogresshud.m file.please help.

**Comment by honkmaster** [comment]
How to reproduce? Please follow the issue guidelines (https://github.com/necolas/issue-guidelines/blob/master/CONTRIBUTING.md#bugs) to help me solve the issue.
