### ISSUE TITLE
How to set SV_APP_EXTENSIONS

### ISSUE THREAD

**Issue by avshiyanov** [TransitApp/SVProgressHUD#480]
If I set #define SV_APP_EXTENSIONS it does not work for me

**Comment by avshiyanov** [comment]
How it use together with setViewForExtension ?

**Comment by avshiyanov** [comment]
I didn't find any example in demo app

**Comment by honkmaster** [comment]
`SV_APP_EXTENSIONS ` is a preprocessor macro. Add the files to your extension, set `SV_APP_EXTENSIONS`to `1` and before calling `show` use `setViewForExtension` with `self.view`.
