### ISSUE TITLE
Incorrect tint color when calling showImage:status: with an UIImage that has its renderingMode different than UIImageRenderingModeAlwaysTemplate

### ISSUE THREAD

**Issue by bhapca** [TransitApp/SVProgressHUD#481]
Steps to reproduce:
1. Set the default style to SVProgressHUDStyleDark.
2. Load a dark-colored UIImage (e.g. from the app bundle).
3. Pass that image to the showImage:status:. The shown image will be very hard to distinguish from the background. 

You can see these steps in change I made to the official Demo app, shown at https://github.com/bhapca/SVProgressHUD/commit/34dd7b140871a67a1bd3e491eb9a4f446704a172. To see it in action run the changed Demo app and tap the "showSuccessWithStatus:" button.

The results are as shown below:
![ios simulator screen shot 14 sep 2015 15 33 30](https://cloud.githubusercontent.com/assets/7116742/9851987/7d025076-5b04-11e5-959f-f041f18b76c7.png)

The problem seems to be caused by the fact that showImage:status: eventually uses the tintColor of UIImageView, which, according to the docs, only works for template images.

**Comment by honkmaster** [comment]
Very good bug description, thank you.
