### ISSUE TITLE
SVProgressHUD can't setAlpha

### ISSUE THREAD

**Issue by teacher-too** [TransitApp/SVProgressHUD#483]
In the latest features ,I don't know how to setAlpha,and the time is so short.
If setAlpha Modify the source code，setAlpha < 1.0f, the SVProgressHUD can't dismiss.
Please tell me, Thanks.

**Comment by honkmaster** [comment]
Please follow the issue guidelines (https://github.com/necolas/issue-guidelines/blob/master/CONTRIBUTING.md#bugs) to help me solve the issue.

**Comment by teacher-too** [comment]
Sorry,I'm a newbie.
I just learned two weeks, many look not to understand.
so,At the moment,I don't have this ability.
Hope other masters can solve the issue.
