### ISSUE TITLE
First HUD display always has no background

### ISSUE THREAD

**Issue by allaire** [TransitApp/SVProgressHUD#486]
Weird stuff, the first HUD that I show always has no background, but every subsequent HUD has one according to the appearance I've set in my app delegate. Using latest head.

Thanks!

**Comment by honkmaster** [comment]
Do you have any idea how to reproduce this issue? I have the HUD in multiple apps with the current head and also the demo project. Here, everything seems to be OK.

**Comment by allaire** [comment]
Calling:
```
        SVProgressHUD.setDefaultStyle(SVProgressHUDStyle.Light)
        SVProgressHUD.setDefaultMaskType(SVProgressHUDMaskType.Black)
```

in didFinishLaunchingWithOptions, then normally displaying HUD like that:

`SVProgressHUD.showWithStatus(t("status.loading"))`

**Comment by honkmaster** [comment]
Hi, can not reproduce your issue when using the demo project and the instructions provided. However, you are using Swift, the demo is ObjC ... even though i don`t think this is the problem.

**Comment by allaire** [comment]
I think there is a difference in some loading priority with Swift vs Objective-C, might have to spin a demo project

**Comment by allaire** [comment]
@honkmaster Alright, just created a demo project that shows 2 issues, you can download it here: https://dl.dropboxusercontent.com/u/7817397/SVProgressHudTest.zip

1) the HUD is not taking any into account any appearance that is set in the `App Delegate` or in the `viewDidLoad`. I can get it to work if I comment the two `setDefaultStyle` lines in `AppDelegate` and add them just before the `show` in `viewDidLoad`. The weird thing is if you don't remove the two `setDefaultStyle` lines in App Delegate, it won't work!

2) The HUD won't show up at all if you try to display it in `viewDidLoad`

If you need more assistance, don't hesitate!

Thanks!

**Comment by allaire** [comment]
@honkmaster I built a wrapper class which calls the appearance methods before each time I show a HUD (this seems like a good temporary fix):

```swift
class ProgressHUDManager {
    
    class func initStyles() {
        SVProgressHUD.setDefaultStyle(SVProgressHUDStyle.Light)
        SVProgressHUD.setDefaultMaskType(SVProgressHUDMaskType.Gradient)
    }
    
    class func dismiss() {
        SVProgressHUD.dismiss()
    }
    
    class func loadingStatus() {
        genericStatus(t("status.loading"))
    }
    
    class func savingStatus() {
        genericStatus(t("status.saving"))
    }
    
    class func uploadingStatus() {
        genericStatus(t("status.uploading"))
    }
    
    class func signInStatus() {
        genericStatus(t("status.signin.signing_in"))
    }
    
    class func thanksInterestSuccess() {
        genericSuccessWithStatus(t("status.thanks_interest"))
    }
    
    class func savedSuccess() {
        genericSuccessWithStatus(t("status.saved"))
    }
    
    class func savedCommentDocument() {
        genericSuccessWithStatus(t("status.comments.document_saved"))
    }
    
    class func signInError() {
        genericError(t("status.signin.error"))
    }
    
    class func signInFacebookError() {
        genericError(t("status.signin.facebook_error"))
    }
    
    class func serverError() {
        genericError(t("status.server_error"))
    }
    
    class func validationError(error: JSON) {
        genericError("TODO: Show the error")
    }
    
    class func authTokenError() {
        genericError(t("status.auth_token_error"))
    }
    
    class func signInUnconfirmedInfo() {
        genericInfoWithStatus(t("status.signin.unconfirmed_info"))
    }
    
    class func myRequestConfirmInfo() {
        genericInfoWithStatus(t("status.my_requests.confirm_info"))
    }
    
    class func availabilityListConfirmInfo() {
        genericInfoWithStatus(t("status.availability_list.confirm_info"))
    }
    
    class func genericInfoWithStatus(message: String) {
        initStyles()
        SVProgressHUD.showInfoWithStatus(message)
    }

    class func genericSuccessWithStatus(message: String) {
        initStyles()
        SVProgressHUD.showSuccessWithStatus(message)
    }
    
    class func genericStatus(message: String) {
        initStyles()
        SVProgressHUD.showWithStatus(message)
    }
    
    class func genericError(message: String) {
        initStyles()
        SVProgressHUD.showErrorWithStatus(message)
    }

}
```

**Comment by honkmaster** [comment]
The issue for 2. (viewDidLoad) is that `[UIApplication sharedApplication].keyWindow` is nil and therefore we can not get the dimension for the view. I try to fix this now. After this I will tackle the rest.

**Comment by allaire** [comment]
@honkmaster Cool keep me posted if you need help with something (tests, etc.)!

**Comment by maqen** [comment]
I can confirm this simply doing

```swift
SVProgressHUD.show()
SVProgressHUD.dismiss()
SVProgressHUD.show()
```
Give me the correct "theme" set in app delegate. Doing the first call ```SVProgressHUD.show()``` results in an unstyled "default" HUD.

**Comment by allaire** [comment]
@maqen Yeah, I thought of doing this, but too hackish for me :P

**Comment by ndmeiri** [comment]
+1 Seeing the same issue

**Comment by sagarsurani** [comment]
you have to set appearance before show

**Comment by ndmeiri** [comment]
@sagarsurani That does not fix the issue for me.

**Comment by allaire** [comment]
@honkmaster Did you fix this in the latest beta? Do you want me to check on my side?

thanks!

**Comment by honkmaster** [comment]
I implemented the Solution for the problem I identified earlier (where the keyWindow is nil). Should be fixed, please verify.

**Comment by allaire** [comment]
@honkmaster According to my project this is now working great. So I guess #2 also fixed the styling issue that was not working on first HUD shown? Care to point to the commit which fixed the issue?

Will close this one, thanks!

**Comment by honkmaster** [comment]
This commit fixed the issue: https://github.com/TransitApp/SVProgressHUD/commit/b4a62cde8c7122a6a0fdee62a3bae690f49ea914

**Comment by allaire** [comment]
@honkmaster Ah, roger that. From what I see here http://stackoverflow.com/questions/21698482/diffrence-between-uiapplication-sharedapplication-delegate-window-and-u the difference is pretty vague between keyWindow and delegate, care to explain why it changes something in SVProgressHUD's case?

**Comment by honkmaster** [comment]
The `keyWindow` is nil if `makeKeyAndVisible` was not called before => The HUD thus had no idea about what frame to use. However, the delegate window is set even before the app is startet and represents the context in which the app is displayed. They are the same AFTER the app has launched.

**Comment by allaire** [comment]
Makes sense thanks!

**Comment by allaire** [comment]
@honkmaster Oh and while I have you here (and to avoid opening an already fixed issue). I noticed that sometimes (not always), some of my HUDs were dismissing really really fast. I know some mechanics was added to take into consideration the text length, maybe at some point this was not working correctly?

It seems better now that I updated to 2.0 though!

Thanks for all your time!

**Comment by honkmaster** [comment]
The mechanics therefore are in place for several years, we just recently added a function to set the minimum display time. Nothing was really changed here.

**Comment by allaire** [comment]
@honkmaster Ah alright, maybe it was some weird glitch! thanks
