### ISSUE TITLE
How to create separate instances for use with multiple tabs?

### ISSUE THREAD

**Issue by andrewhavens** [TransitApp/SVProgressHUD#488]
I have an app with multiple tabs. Each tab displays a SVProgressHUD loading icon. But if one tab has finished loading earlier than the other one, it dismisses the loading icon early (since there is only one global loading icon). How can I deal with this scenario? Ideally, if I could create an instance of a loading icon and attach it to a view, then I could have two separate loading icons in each tab.

**Comment by honkmaster** [comment]
The HUD is designed as a singleton instance. At the moment such a use case is not intended. However a PR is welcome.
