### ISSUE TITLE
center of screen issue solved

### ISSUE THREAD

**Issue by mohsinalimat** [TransitApp/SVProgressHUD#489]
Hello,

for center of screen use below code...

- (void)moveToPoint:(CGPoint)newCenter rotateAngle:(CGFloat)angle{
    self.hudView.transform = CGAffineTransformMakeRotation(angle);
//    self.hudView.center = CGPointMake(newCenter.x + self.offsetFromCenter.horizontal, newCenter.y + self.offsetFromCenter.vertical);
    self.hudView.center = CGPointMake(([UIScreen mainScreen].bounds.size.width)/2, ([UIScreen mainScreen].bounds.size.height)/2);
}

Thanks, 
Mohsinali Matiya

**Comment by nihilenz** [comment]
I also have a serious position problem. The first time the HUD is presented at the center of the screen, then is at the top, partially out of screen.

Your solution is almost ok, but with SVProgressHUDMaskTypeGradient the gradient is at the top.

**Comment by honkmaster** [comment]
At first you have to describe the bug better and provide a sample project. I will not just exchange code based on such a small notice. Sorry.
