### ISSUE TITLE
No supported interface orientation in real time

### ISSUE THREAD

**Issue by zarochintsev** [TransitApp/SVProgressHUD#490]
No supported interface orientation in real time. It was seen on iOS 9.1 Public beta.

If progress hud is visible and flip the device, the background will be in the same position.

**Comment by zarochintsev** [comment]
![image](https://cloud.githubusercontent.com/assets/5650844/10203594/9eed73ec-67bf-11e5-8b74-8d8e2658c301.png)

**Comment by estebansotoara** [comment]
Hi, 
it is possible that there is an error in the validation in SVProgressHUD.m line 583? I changed it and it is updating the HUD properly when the orientation is changed but I currently can only test in an iPhone 5 so there is a chance that this solution could fail in other devices. 

I made a fork with this solution (https://github.com/estebansotoara/SVProgressHUD/tree/support_interface_orientation), I can make a PR if it is needed.

**Comment by honkmaster** [comment]
@davidolesch could you please check if this is a bug in line 583 as described?

**Comment by davidolesch** [comment]
@honkmaster I am on vacation this week but have made a note to investigate this on Monday.

**Comment by davidolesch** [comment]
@honkmaster yes that's a bug in my code. @estebansotoara made the correct change [here](https://github.com/estebansotoara/SVProgressHUD/commit/1e35a3af63d3c335d9785d89dba4700af2b402a0).

**Comment by estebansotoara** [comment]
I created a pull request (#512),  I'm glad it worked
