### ISSUE TITLE
Is the README out of date or is + setCornerRadius missing? 

### ISSUE THREAD

**Issue by cameronehrlich** [TransitApp/SVProgressHUD#493]

**Comment by honkmaster** [comment]
There is no method `setColorRadius`. Do you mean: `setCornerRadius`.

**Comment by cameronehrlich** [comment]
Yes, my bad. :smile:

**Comment by honkmaster** [comment]
I do not see the method missing.

**Comment by cameronehrlich** [comment]
I just checked out my Podfile and see that I am using:

```pod 'SVProgressHUD', '~> 1.1'```

On here, the podspec says it's on version `1.1.3`.  
Maybe that's why it's not there! haha

I thought I had run `pod outdated` and didn't see this come up.  
I'll check again tonight and see if it's still an issue, but it sounds like my mistake.
