### ISSUE TITLE
Add support for tvOS

### ISSUE THREAD

**Issue by davidolesch** [TransitApp/SVProgressHUD#496]
As far as I can tell the main challenge is that UIInterfaceOrientation and related orientation properties on UIApplication aren't available on tvOS.

**Comment by davidolesch** [comment]
![screen shot 2015-10-20 at 1 51 21 pm](https://cloud.githubusercontent.com/assets/1456095/10617750/b1fdad68-7731-11e5-961e-306f27a3d384.png)

**Comment by honkmaster** [comment]
This should be easy to solve <=> those values are constant for tvOS and thus can be hardcoded somehow. PR is welcome.

**Comment by davidolesch** [comment]
@honkmaster I've started working on it.

On [this line](https://github.com/TransitApp/SVProgressHUD/blob/9dd505fd1a6bb9015199c00efa3e5a7df5f13128/SVProgressHUD/SVProgressHUD.m#L518) why is there a ternary operator where both results are the same?

**Comment by davidolesch** [comment]
![svprogresshud_on_tvos](https://cloud.githubusercontent.com/assets/1456095/10668616/c249840e-78a2-11e5-93b4-17b860ca056f.gif)

**Comment by honkmaster** [comment]
Very cool. Will review soon in one of my own projects and merge after I confirmed the functionality if this is OK for you.

**Comment by davidolesch** [comment]
Sounds great.

**Comment by davidolesch** [comment]
@honkmaster let me know if I can help with QA so that this can get merged.

**Comment by honkmaster** [comment]
Hi, I will merge this now. However, It would be great if you can add a demo application to the project so we could easily check the components functionality on tvOS each time a new addition is made.

**Comment by davidolesch** [comment]
@honkmaster so an equivalent to [this](https://github.com/TransitApp/SVProgressHUD/tree/master/Demo) but for tvOS? I can work on that.

**Comment by honkmaster** [comment]
yep.

**Comment by honkmaster** [comment]
Should be merged.
