### ISSUE TITLE
bitcode bundle could not be generated because '/Users/mcspx/Documents/Apple-Developer/toolstracker/Carthage/Build/iOS/SVProgressHUD.framework/SVProgressHUD' was built without full bitcode. All frameworks and dylibs for bitcode must be generated from Xcode Archive or Install build for architecture armv7

### ISSUE THREAD

**Issue by jassadakorn** [TransitApp/SVProgressHUD#506]
bitcode bundle could not be generated because '/Users/mcspx/Documents/Apple-Developer/toolstracker/Carthage/Build/iOS/SVProgressHUD.framework/SVProgressHUD' was built without full bitcode. All frameworks and dylibs for bitcode must be generated from Xcode Archive or Install build for architecture armv7

**Comment by honkmaster** [comment]
Can not reproduce in demo project.
