### ISSUE TITLE
Crash: 1.1.3 NSBundle

### ISSUE THREAD

**Issue by yimiaodaren** [TransitApp/SVProgressHUD#526]
NSBundle *bundle = [NSBundle bundleForClass:self.class];
    NSURL *url = [bundle URLForResource:@"SVProgressHUD" withExtension:@"bundle"];
    NSBundle *imageBundle = [NSBundle bundleWithURL:url];

this code block is in "SVIndefiniteAnimatedView.m" lines 60~62  and "SVProgressHUD.m" lines 265~267.
url == nil  ,  and carsh in   [NSBundle bundleWithURL:nil];
in SVProgressHUD 1.1.3 ,  Xcode 7.2 , cocoaPods 0.39.0

**Comment by honkmaster** [comment]
Have you run `pod install`? Did you tried the latest 2.0?

**Comment by yimiaodaren** [comment]
maybe i find the reason that i update the mac to 10.11.2 and xcode to 7.2 ..  and i run pod install when the xcode is updating... 3Q
