### ISSUE TITLE
SVProgressHUD appearance not working in 2.0 beta version

### ISSUE THREAD

**Issue by demonotter** [TransitApp/SVProgressHUD#534]
So I was using version 1.3, and set background color with 
[SVProgressHUD setBackgroundColor:[[UIColor blackColor] colorWithAlphaComponent:0.5]];
And everything worked fine.
After update to 2.0, I tried to set it with [SVProgressHUD appearance] and it is not working.
Actually, first method is not working either.

**Comment by honkmaster** [comment]
have you set `SVProgressHUDStyleCustom`?

**Comment by demonotter** [comment]
Sorry. My bad. I haven't done this step

**Comment by honkmaster** [comment]
No problem, you are welcome. If you have any other questions keep me updated.
